name: FFMPEG

on:
  push:
    branches: [main]

jobs:
  build:
    name: Build
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Merge from master
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git fetch --all
          git checkout gh-pages
          git merge main --no-ff

      - name: Install FFMPEG
        run: sudo apt-get update && sudo apt-get install ffmpeg curl

      - name: Run Build
        run: cd movie && ffmpeg -f concat -i playlist.txt playlist.m3u8

      - name: Make Commit
        run: |
          git add .
          git commit -m "[auto] Generate HLS File"
          git push
